sever:
  port:8080
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
  jpa:
    database: mysql
    show-sql: true