server: 
  port: 8081
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_recruit?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
  jpa: 
    database: MySQL
    show-sql: true
